site_name: db-migrate
pages:
- [content/search.html, Search through the docs]
- [content/home.md, Home]
- [content/help.md, 'Helping db-migrate']
- [content/Getting Started/installation.md, 'Getting Started', Installation]
- [content/Getting Started/configuration.md, 'Getting Started', Configuration]
- [content/Getting Started/the commands.md, 'Getting Started', 'The Commands']
- [content/Getting Started/usage.md, 'Getting Started', Usage]
- [content/API/generic datatypes.md, 'API', 'Generic Datatypes']
- [content/API/SQL.md, 'API', 'SQL API']
- [content/API/NoSQL.md, 'API', 'NoSQL API']
- [content/API/programable.md, 'API', 'Programable API']
- [content/Developers/running tests.md, 'Developers', 'Running Tests']
- [content/Developers/contributing.md, 'Developers', Contributing]
docs_dir: .
repo_url: https://github.com/db-migrate/english-docs
theme: readthedocs
